# Generated by Django 2.0.3 on 2018-03-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
