# Generated by Django 2.0.3 on 2018-03-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0002_auto_20180330_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='applied_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='sop',
            field=models.TextField(default='Hi'),
        ),
    ]
